package io.github.pia300.highlightreplay.ui.theme

import androidx.compose.ui.graphics.Color

/** 静态（非动态）蓝色主题的浅色配色方案。 */
val LightStaticColors = androidx.compose.material3.lightColorScheme(
    primary = Color(0xFF1A5FA8),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFD4E3FF),
    onPrimaryContainer = Color(0xFF001C3A),
    secondary = Color(0xFF555F71),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFD8E3F8),
    onSecondaryContainer = Color(0xFF111C2B),
    tertiary = Color(0xFF6E5676),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFF7D8FF),
    onTertiaryContainer = Color(0xFF271430),
    error = StatusCaptureLostBase,
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = StatusCaptureLostDarkIconBase,
    background = Color(0xFFFDFCFF),
    onBackground = Color(0xFF1A1C1E),
    surface = Color(0xFFFDFCFF),
    onSurface = Color(0xFF1A1C1E),
    surfaceVariant = Color(0xFFE0E2EC),
    onSurfaceVariant = Color(0xFF43474E),
    outline = Color(0xFF74777F),
    outlineVariant = Color(0xFFC3C6CF),
    inverseSurface = Color(0xFF2F3033),
    inverseOnSurface = Color(0xFFF1F0F4),
    inversePrimary = Color(0xFFA6C8FF),
    surfaceTint = Color(0xFF1A5FA8),
    surfaceDim = Color(0xFFDAD9DD),
    surfaceBright = Color(0xFFFAF9FD),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFF4F3F7),
    surfaceContainer = Color(0xFFEEEDF1),
    surfaceContainerHigh = Color(0xFFE9E8EB),
    surfaceContainerHighest = Color(0xFFE3E2E6),
    scrim = Color(0xFF000000)
)
/** 静态（非动态）蓝色主题的深色配色方案。 */
val DarkStaticColors = androidx.compose.material3.darkColorScheme(
    primary = Color(0xFFA6C8FF),
    onPrimary = Color(0xFF00315F),
    primaryContainer = Color(0xFF004786),
    onPrimaryContainer = Color(0xFFD4E3FF),
    secondary = Color(0xFFBCC7DC),
    onSecondary = Color(0xFF273141),
    secondaryContainer = Color(0xFF3D4758),
    onSecondaryContainer = Color(0xFFD8E3F8),
    tertiary = Color(0xFFDABDE2),
    onTertiary = Color(0xFF3D2846),
    tertiaryContainer = Color(0xFF553F5D),
    onTertiaryContainer = Color(0xFFF7D8FF),
    error = StatusCaptureLostDarkBase,
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF121316),
    onBackground = Color(0xFFE3E2E6),
    surface = Color(0xFF121316),
    onSurface = Color(0xFFE3E2E6),
    surfaceVariant = Color(0xFF43474E),
    onSurfaceVariant = Color(0xFFC3C6CF),
    outline = Color(0xFF8D9199),
    outlineVariant = Color(0xFF43474E),
    inverseSurface = Color(0xFFE3E2E6),
    inverseOnSurface = Color(0xFF2F3033),
    inversePrimary = Color(0xFF1A5FA8),
    surfaceTint = Color(0xFFA6C8FF),
    surfaceDim = Color(0xFF121316),
    surfaceBright = Color(0xFF38393C),
    surfaceContainerLowest = Color(0xFF0D0E11),
    surfaceContainerLow = Color(0xFF1A1C1E),
    surfaceContainer = Color(0xFF1E2023),
    surfaceContainerHigh = Color(0xFF292A2D),
    surfaceContainerHighest = Color(0xFF343538),
    scrim = Color(0xFF000000)
)

/** 绿色主题的浅色配色方案。 */
val LightGreenColors = androidx.compose.material3.lightColorScheme(
    primary = Color(0xFF1B6D24),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFA3F69C),
    onPrimaryContainer = Color(0xFF002204),
    secondary = Color(0xFF52634F),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFD6E8CE),
    onSecondaryContainer = Color(0xFF111F0F),
    tertiary = Color(0xFF38656A),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFBCEBF0),
    onTertiaryContainer = Color(0xFF002023),
    error = StatusCaptureLostBase,
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = StatusCaptureLostDarkIconBase,
    background = Color(0xFFFCFDF6),
    onBackground = Color(0xFF1A1C19),
    surface = Color(0xFFFCFDF6),
    onSurface = Color(0xFF1A1C19),
    surfaceVariant = Color(0xFFDEE5D8),
    onSurfaceVariant = Color(0xFF424940),
    outline = Color(0xFF72796F),
    outlineVariant = Color(0xFFC2C9BD),
    inverseSurface = Color(0xFF2F312D),
    inverseOnSurface = Color(0xFFF0F1EB),
    inversePrimary = Color(0xFF88D982),
    surfaceTint = Color(0xFF1B6D24),
    surfaceDim = Color(0xFFDADAD4),
    surfaceBright = Color(0xFFF9FAF3),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFF3F4EE),
    surfaceContainer = Color(0xFFEEEEE8),
    surfaceContainerHigh = Color(0xFFE8E9E2),
    surfaceContainerHighest = Color(0xFFE2E3DD),
    scrim = Color(0xFF000000)
)
/** 绿色主题的深色配色方案。 */
val DarkGreenColors = androidx.compose.material3.darkColorScheme(
    primary = Color(0xFF88D982),
    onPrimary = Color(0xFF003909),
    primaryContainer = Color(0xFF005312),
    onPrimaryContainer = Color(0xFFA3F69C),
    secondary = Color(0xFFBACCB3),
    onSecondary = Color(0xFF253423),
    secondaryContainer = Color(0xFF3B4B38),
    onSecondaryContainer = Color(0xFFD6E8CE),
    tertiary = Color(0xFFA0CFD4),
    onTertiary = Color(0xFF00363B),
    tertiaryContainer = Color(0xFF1F4D52),
    onTertiaryContainer = Color(0xFFBCEBF0),
    error = StatusCaptureLostDarkBase,
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF121411),
    onBackground = Color(0xFFE2E3DD),
    surface = Color(0xFF121411),
    onSurface = Color(0xFFE2E3DD),
    surfaceVariant = Color(0xFF424940),
    onSurfaceVariant = Color(0xFFC2C9BD),
    outline = Color(0xFF8C9388),
    outlineVariant = Color(0xFF424940),
    inverseSurface = Color(0xFFE2E3DD),
    inverseOnSurface = Color(0xFF2F312D),
    inversePrimary = Color(0xFF1B6D24),
    surfaceTint = Color(0xFF88D982),
    surfaceDim = Color(0xFF121411),
    surfaceBright = Color(0xFF383A36),
    surfaceContainerLowest = Color(0xFF0C0F0C),
    surfaceContainerLow = Color(0xFF1A1C19),
    surfaceContainer = Color(0xFF1E201D),
    surfaceContainerHigh = Color(0xFF282B27),
    surfaceContainerHighest = Color(0xFF333531),
    scrim = Color(0xFF000000)
)

/** 紫色主题的浅色配色方案。 */
val LightPurpleColors = androidx.compose.material3.lightColorScheme(
    primary = Color(0xFF6750A4),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFE9DDFF),
    onPrimaryContainer = Color(0xFF22005D),
    secondary = Color(0xFF625B71),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFE8DEF8),
    onSecondaryContainer = Color(0xFF1E192B),
    tertiary = Color(0xFF7E5260),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFFFD9E3),
    onTertiaryContainer = Color(0xFF31101D),
    error = StatusCaptureLostBase,
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = StatusCaptureLostDarkIconBase,
    background = Color(0xFFFFFBFF),
    onBackground = Color(0xFF1C1B1E),
    surface = Color(0xFFFFFBFF),
    onSurface = Color(0xFF1C1B1E),
    surfaceVariant = Color(0xFFE7E0EB),
    onSurfaceVariant = Color(0xFF49454E),
    outline = Color(0xFF7A757F),
    outlineVariant = Color(0xFFCAC4CF),
    inverseSurface = Color(0xFF313033),
    inverseOnSurface = Color(0xFFF4EFF4),
    inversePrimary = Color(0xFFCFBCFF),
    surfaceTint = Color(0xFF6750A4),
    surfaceDim = Color(0xFFDDD8DD),
    surfaceBright = Color(0xFFFDF8FD),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFF7F2F7),
    surfaceContainer = Color(0xFFF2ECF1),
    surfaceContainerHigh = Color(0xFFECE7EB),
    surfaceContainerHighest = Color(0xFFE6E1E6),
    scrim = Color(0xFF000000)
)
/** 紫色主题的深色配色方案。 */
val DarkPurpleColors = androidx.compose.material3.darkColorScheme(
    primary = Color(0xFFCFBCFF),
    onPrimary = Color(0xFF381E72),
    primaryContainer = Color(0xFF4F378A),
    onPrimaryContainer = Color(0xFFE9DDFF),
    secondary = Color(0xFFCBC2DB),
    onSecondary = Color(0xFF332D41),
    secondaryContainer = Color(0xFF4A4458),
    onSecondaryContainer = Color(0xFFE8DEF8),
    tertiary = Color(0xFFEFB8C8),
    onTertiary = Color(0xFF4A2532),
    tertiaryContainer = Color(0xFF633B48),
    onTertiaryContainer = Color(0xFFFFD9E3),
    error = StatusCaptureLostDarkBase,
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF141316),
    onBackground = Color(0xFFE6E1E6),
    surface = Color(0xFF141316),
    onSurface = Color(0xFFE6E1E6),
    surfaceVariant = Color(0xFF49454E),
    onSurfaceVariant = Color(0xFFCAC4CF),
    outline = Color(0xFF948F99),
    outlineVariant = Color(0xFF49454E),
    inverseSurface = Color(0xFFE6E1E6),
    inverseOnSurface = Color(0xFF313033),
    inversePrimary = Color(0xFF6750A4),
    surfaceTint = Color(0xFFCFBCFF),
    surfaceDim = Color(0xFF141316),
    surfaceBright = Color(0xFF3A383C),
    surfaceContainerLowest = Color(0xFF0F0E11),
    surfaceContainerLow = Color(0xFF1C1B1E),
    surfaceContainer = Color(0xFF201F22),
    surfaceContainerHigh = Color(0xFF2B292D),
    surfaceContainerHighest = Color(0xFF363438),
    scrim = Color(0xFF000000)
)

/** 橙色主题的浅色配色方案。 */
val LightOrangeColors = androidx.compose.material3.lightColorScheme(
    primary = Color(0xFF8B5000),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFFFDCBE),
    onPrimaryContainer = Color(0xFF2D1600),
    secondary = Color(0xFF735A42),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFFFDCBE),
    onSecondaryContainer = Color(0xFF291806),
    tertiary = Color(0xFF586339),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFDCE8B4),
    onTertiaryContainer = Color(0xFF161E00),
    error = StatusCaptureLostBase,
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = StatusCaptureLostDarkIconBase,
    background = Color(0xFFFFFBFF),
    onBackground = Color(0xFF201B16),
    surface = Color(0xFFFFFBFF),
    onSurface = Color(0xFF201B16),
    surfaceVariant = Color(0xFFF2DFD1),
    onSurfaceVariant = Color(0xFF51453A),
    outline = Color(0xFF837468),
    outlineVariant = Color(0xFFD5C3B5),
    inverseSurface = Color(0xFF352F2B),
    inverseOnSurface = Color(0xFFFAEFE7),
    inversePrimary = Color(0xFFFFB871),
    surfaceTint = Color(0xFF8B5000),
    surfaceDim = Color(0xFFE3D8D1),
    surfaceBright = Color(0xFFFFF8F5),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFFDF1EA),
    surfaceContainer = Color(0xFFF7ECE5),
    surfaceContainerHigh = Color(0xFFF1E6DF),
    surfaceContainerHighest = Color(0xFFEBE0D9),
    scrim = Color(0xFF000000)
)
/** 橙色主题的深色配色方案。 */
val DarkOrangeColors = androidx.compose.material3.darkColorScheme(
    primary = Color(0xFFFFB871),
    onPrimary = Color(0xFF4A2800),
    primaryContainer = Color(0xFF6A3C00),
    onPrimaryContainer = Color(0xFFFFDCBE),
    secondary = Color(0xFFE1C1A4),
    onSecondary = Color(0xFF402C18),
    secondaryContainer = Color(0xFF59422D),
    onSecondaryContainer = Color(0xFFFFDCBE),
    tertiary = Color(0xFFC0CC9A),
    onTertiary = Color(0xFF2B3410),
    tertiaryContainer = Color(0xFF414B24),
    onTertiaryContainer = Color(0xFFDCE8B4),
    error = StatusCaptureLostDarkBase,
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF17120F),
    onBackground = Color(0xFFEBE0D9),
    surface = Color(0xFF17120F),
    onSurface = Color(0xFFEBE0D9),
    surfaceVariant = Color(0xFF51453A),
    onSurfaceVariant = Color(0xFFD5C3B5),
    outline = Color(0xFF9E8E81),
    outlineVariant = Color(0xFF51453A),
    inverseSurface = Color(0xFFEBE0D9),
    inverseOnSurface = Color(0xFF352F2B),
    inversePrimary = Color(0xFF8B5000),
    surfaceTint = Color(0xFFFFB871),
    surfaceDim = Color(0xFF17120F),
    surfaceBright = Color(0xFF3E3833),
    surfaceContainerLowest = Color(0xFF120D0A),
    surfaceContainerLow = Color(0xFF201B16),
    surfaceContainer = Color(0xFF241F1A),
    surfaceContainerHigh = Color(0xFF2E2924),
    surfaceContainerHighest = Color(0xFF3A342F),
    scrim = Color(0xFF000000)
)

/** 状态指示色（浅色主题）：录制中用绿色主题主色。 */
val StatusRecording = LightGreenColors.primary
/** 状态指示色（浅色主题）：就绪时用静态主题主色。 */
val StatusReady = LightStaticColors.primary
/** 状态指示色（深色主题）：录制中为浅绿，引用共享基色（与悬浮窗 AudioBar 同一绿色）。 */
val StatusRecordingDark = StatusActiveGreenBase
/** 状态指示色（深色主题）：就绪时为浅蓝（深色方案无对应 token，固定取值）。 */
val StatusReadyDark = StatusReadyBlueBase

/** “跟随壁纸（动态）”行的示意渐变三色：取蓝/紫/橙主题主色作色标，供预览、非可选色板。 */
val DynamicSwatchColors = listOf(
    LightStaticColors.primary,
    LightPurpleColors.primary,
    LightOrangeColors.primary
)
